movieproject/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove,name='full_remove'),
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL,
             document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

movieproject/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'

urlpatterns= [
    path('', views.SearchResult, name='SearchResult'),
]

movieproject/shop/urls.py
from django.urls import path, include

from . import  views
app_name='shop'
urlpatterns = [

    path('', views.allProCat, name="allProCat"),
    path('<slug:cat_slug>/', views.allProCat, name="products_by_category"),
    path('<slug:cat_slug>/<slug:pro_slug>/', views.productDetail, name="proCatDetail")
]

movieproject/shoproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop',include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls'))

]

if settings.DEBUG :
    urlpatterns += static (settings.STATIC_URL,
                           document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/cart/models.py
from django.db import models

# Create your models here.
from django.db import models
from shop.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=200, blank=True)
    data_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering = ['data_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

movieproject/search_app/models.py
from django.db import models

# Create your models here.

movieproject/shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])
    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:proCatDetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

movieproject/cart/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from cart.models import Cart, CartItem
from shop.models import Product
from django.core.exceptions import ObjectDoesNotExist
#CART
# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart
def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist :
        cart = Cart.objects.create(cart_id=_cart_id(request))
    try :
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock :
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity = 1,
            cart = cart
        )
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for i in cart_items:
            total += (i.product.price * i.quantity)
            counter += i.quantity

    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total))
def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1 :
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

movieproject/search_app/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

movieproject/shop/views.py
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
# Create your views here.
def allProCat(request, cat_slug=None):
    cat_page = None
    products_list = None
    if cat_slug!=None:
        cat_page = get_object_or_404(Category, slug=cat_slug)
        #showing 404 page if cat_page is not present
        products_list = Product.objects.all().filter(category=cat_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    my_paginator = Paginator(products_list, 3)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = my_paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = my_paginator.page(my_paginator.num_pages)
    return render(request, "category.html", {'cat_key': cat_page, 'pro_key': products})
def productDetail(request,cat_slug,pro_slug):
    try:
        product = Product.objects.get(category__slug=cat_slug, slug=pro_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html',{'product':product})

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %} {% endblock %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'css/style1.css' %}" rel="stylesheet" >

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">

    <!-- icon kit -->
    <script src="https://kit.fontawesome.com/0d8f0b13af.js" crossorigin="anonymous"></script>

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>

</body>
</html>

movieproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Welcome to mySho cart
{% endblock %}
{% block title %}
        mySho-cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div class="container">
  <div class="text-center">
    <h2 class="my_title"> Your Shopping Cart </h2>
    <p> Click <a href="{% url 'shop:allProCat' %}"> here </a> to continue your shopping</p>
  </div>
</div>
{% endif %}
<div>
  {% if cart_items %}
  <div>
    <h1 class="text-center my_title"> Your Shopping Cart </h1>
  </div>
  <div class="row mx-auto">

    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table my_table">
        <thead class="my_thead">
        <tr>
          <th colspan="5">
            Your Cart Items
          </th>
        </tr>
        </thead>
        <tbody>
        {% for i in cart_items %}
        <tr>
          <td>

              <img src="{{i.product.image.url}}" class="float-left rounded" alt="img-product" width="150px">

          </td>

          <td>
            {{i.product.name}}
            <br>
            SKU: {{i.product.id}}
            <br>
            Price: Rs {{i.product.price}}
            <br>
            Qty: {{i.quantity}} x Rs {{i}}
          </td>
          <td>
            Rs {{i.sub_total}}
          </td>
          {% if i.quantity < i.product.stock %}
          <td>
            <a href="{% url 'cart:add_cart' i.product.id %}">
              <i class="fa-solid fa-plus"> </i>  </a> &nbsp;
            <a href="{% url 'cart:cart_remove' i.product.id %}">
              <i class="fa-solid fa-minus"> </i> &nbsp; </a> &nbsp;
            <a href="{% url 'cart:full_remove' i.product.id %}">
              <i class="fa-solid fa-trash"> </i> &nbsp; </a>
          </td>
          {% else %}
          <td style="text-justify">
            <a href="{% url 'cart:cart_remove' i.product.id %}">
              <i class="fa-solid fa-minus"> </i> </a> &nbsp;
            <a href="{% url 'cart:full_remove' i.product.id %}">
              <i class="fa-solid fa-trash"> </i> </a> &nbsp;
          </td>
          {% endif %}

        </tr>
        {% endfor %}

        </tbody>
      </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table my_table">
        <thead class="my_thead">
        <tr>
          <th>
          Checkout
          </th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>
            Please review your cart items
          </td>
        </tr>
        <tr>
          <td>
            Your Total is: {{ total }}
          </td>
        </tr>
        </tbody>
      </table>
      <div class="max-auto">
        <a href="{% url 'shop:allProCat' %}" class="btn btn-secondary"> Continue Shopping </a>
      </div> <br>
      <div class="max-auto">
        <a href="{% url 'shop:allProCat' %}" class="btn btn-secondary"> Payment </a>
      </div>
    </div>
  </div>
     {% endif %}
</div>
{% endblock %}

movieproject/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if cat_key %}
        {{ cat_key.description| truncatewords:155}}
    {% else %}
        Welcome to GROCERY
    {% endif %}
{% endblock %}

{% block title %}
    {% if cat_key %}
        GROCERY-{{ cat_key.name }}
    {% else %}
        See our new collection
    {% endif %}
{% endblock %}
{% block content %}
    {% if cat_key %}
    <div>
        <div class="row my_row">
            <div class="mx-auto">
                <p> <a href="{% url 'shop:allProCat' %}"> Our product collectoins </a> </p>
            </div>
        </div>
    </div>
    {% endif %}

 {% if cat_key %}
        <div>
            <img src="{{cat_key.image.url}}" alt="category_image" width="100%"> <br>
        </div>
        <div>
            <h1 class="text-center my_title"> {{cat_key.name}} </h1>
            <p class="text-justify"> {{cat_key.description}} </p>
        </div>

    {% else %}
        <div >
            <img class="my_image_padding" src="{% static 'img/banner.png' %}" alt="static/img/banner.png"  width="100%" > <br>
        </div>
        <div>
            <h1 class="text-center my_title" > Our popular collections </h1>
            <p class="text-justify my_content">Trust us!! our website  provides you fresh vegetables and lovely fruit </p>
        </div>
    {% endif %}
<div class="container">
    <div class="row">
        {% for product in pro_key.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" >
                <a class="card-img-top my_image_padding" href="{{product.get_url}}">
                    <img src="{{product.image.url}}" alt="product image" height="200px" width="auto"> </a>
                <div>
                    <h4> {{ product.name }} </h4>
                    <p> {{ product.price }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if pro_key.paginator.num_pages > 1 %}
        <hr>
            <div class="text-center">
                {% for pg in pro_key.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-dark btn-sm {% if pro_key.number == pg %} active {% endif %}">
                        {{pg}} </a>
                {% endfor %}
            </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

movieproject/templates/footer.html
<footer class="text-center text-lg-start bg-dark text-white">
    <section class="container d-flex justify-content-center justify-content-lg-between p-4">
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <div>
        <a href="" class="me-4 text-reset"><i class="fa fa-facebook"></i></a>
        <a href="" class="me-4 text-reset"><i class="fa fa-twitter"></i></a>
        <a href="" class="me-4 text-reset"><i class="fa fa-google"></i></a>
        <a href="" class="me-4 text-reset"><i class="fa fa-instagram"></i></a>
        <a href="" class="me-4 text-reset"><i class="fa fa-linkedin"></i></a>
        <a href="" class="me-4 text-reset"><i class="fa fa-github"></i></a>
      </div>
    </section>

    <section class="">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4"><i class="fa fa-cart-plus"></i> groceryKart</h6>
            <p>
              groceryKart.com is a one stop destination for your family's health needs.
               We give you the opportunity to give your wardrobe a makeover with the fresh collections from our trustable brands.
            </p>
          </div>

          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">Make Money with Us</h6>
            <p><a href="#!" class="text-reset">Sell on ShopKart</a></p>
            <p><a href="#!" class="text-reset">Advertise Your Products</a></p>
            <p><a href="#!" class="text-reset">Become an Affiliate</a></p>
            <p><a href="#!" class="text-reset">Fulfilment by ShopKart</a></p>
          </div>
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">Useful links</h6>
            <p><a href="#!" class="text-reset">FAQ</a></p>
            <p><a href="#!" class="text-reset">Feedback</a></p>
            <p><a href="#!" class="text-reset">About Us</a></p>
            <p><a href="#!" class="text-reset">Contact Us</a></p>
          </div>

          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold mb-4"> Contact</h6>
            <p><i class="fa fa-home"></i> nasiya </p>
            <p><i class="fa fa-envelope"></i> info@example.com</p>
            <p><i class="fa fa-phone"></i> + 91 9078917009</p>
          </div>

        </div>
      </div>
    </section>
    <div class="text-center p-4">
      &copy;  2023 Copyright <a class="text-reset fw-bold" href="https://grocery.in/"> nasiya.in</a>
    </div>
  </footer>

movieproject/templates/header.html
{% load static %}
<header>
    <center>
    <a href="{% url 'shop:allProCat' %}">
    <img src="{% static 'img/logo.png' %}" alt="logoimage" width="100px;" height="100px;"></a>
    </center>
</header>

movieproject/templates/nav.html
<nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
       <button> <a class="nav-link"  href="{% url 'shop:allProCat' %}" style="color:red;">shop</a>
        </button>

    <ul class="nav navbar-nav mr-auto">
          <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" >
              Category </a>
              <ul class="nav-item dropdown-content" style="list-style-type: none; margin: 0; padding: 0;" >
              <li> <a class="dropdown-item "  href="{% url 'shop:allProCat' %}">All products </a> </li>
              {% for i in links %}
                <li> <a class=" dropdown-item" href="{{i.get_url}}"> {{i.name}} </a> </li>
               {% endfor %}
                </ul>
          </li>
        {% if item_count > 0 %}
        <li class="nav-item">
            <a class="nav-link"  href="{% url 'cart:cart_detail' %}">
                <i class="fa-solid fa-cart-plus"> </i> ({{item_count}})
            </a>
        </li>
        {% endif %}
    </ul>

    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
      <input class="form-control mr-sm-2" name='q' type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            <i class="fa-solid fa-magnifying-glass"></i>
        </button>
    </form>

  </div>
</nav>

movieproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{ product.description| truncatewords:155}}
{% endblock %}
{% block title %}
    {% if cat_key %}
        mySho-{{ product.name }}
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_pro_row">
  <div class="mx_auto">
    <p>
      <a href="{% url 'shop:allProCat' %}"> Home </a> | <a href="{{product.category.get_url}}" > {{product.category}}  </a> | {{product.name}}</p>
  </div>
</div>
<div class="container">
  <br>
  <div class="row">
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <div class="my_image_padding">
      <img  src="{{product.image.url}}" alt="pro image" height="250px" width="auto">
    </div>
  </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
      <h3 class="my_pro_title"> {{product.name}}</h3>
      <p> ${{product.price}} </p>
      <p class="my_highlight"> Highlights </p>
      <p class="text-justify my_pro_text"> ${{product.description}} </p>
      {% if product.stock <= 0 %}
      <p> <b> OUT OF STOCK </b> </p>
      {% else %}
      <div class="my_btn_padding">
        <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %} ">Add to Cart</a>
      </div>

      {% endif %}
    </div>

</div>
</div>
{% endblock %}

movieproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        We have variety of products.
{% endblock %}
{% block title %}
  Search
{% endblock %}
{% block content %}
<div>
  <p class="text-center my_search_text">You have searched for "{{query}}" </p>
</div>

<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" >
                <a class="card-img-top my_image_padding" href="{{product.get_url}}">
                    <img src="{{product.image.url}}" alt="product image" height="200px" width="auto"> </a>
                <div>
                    <h4> {{ product.name }} </h4>
                    <p> {{ product.price }}</p>
                </div>
            </div>
        </div>
      {% empty %}
      <div class="row mx-auto">
        <p class="text-center my_search_text"> 0 Results found</p>
      </div>
      {% endfor %}
  </div>
</div>
{% endblock %}